"""
CONTEXT.md generator — the core differentiator.

Produces a single compressed markdown file that any AI reads at session start.
Replaces CLAUDE.md. Works without MCP, without tooling, with any AI.

Structure:
  ## project       — what this is (written once, stable)
  ## architecture  — module map (updated when structure changes)
  ## conventions   — patterns detected from code (updated when patterns change)
  ## hot files     — most-changed + most-connected files (updated every commit)
  ## recent        — last 7 days of changes (rolling window, auto-rotated)
  ## notes         — manual section, NEVER overwritten by ctxmap

Update model:
  - Each section has a hash of its source inputs
  - On update, only sections whose inputs changed get rewritten
  - LLM called only for sections that need rewriting
  - ~300-600 tokens per typical commit
"""
from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from .store import GraphStore

logger = logging.getLogger(__name__)

CONTEXT_FILE = "CONTEXT.md"
META_FILE = ".ctxmap/section_hashes.json"

SECTION_ORDER = ["project", "architecture", "conventions", "hot_files", "recent", "notes"]

MANUAL_MARKER_START = "<!-- ctxmap:manual -->"
MANUAL_MARKER_END = "<!-- ctxmap:manual:end -->"

SECTION_MARKERS = {
    s: (f"<!-- ctxmap:{s} -->", f"<!-- ctxmap:{s}:end -->")
    for s in SECTION_ORDER
}


# ─── Section input hashing ───────────────────────────────────────────────────

def _hash_inputs(*parts: Any) -> str:
    combined = json.dumps(parts, sort_keys=True, default=str)
    return hashlib.sha256(combined.encode()).hexdigest()[:16]


# ─── Read/write CONTEXT.md ───────────────────────────────────────────────────

def _read_sections(path: Path) -> dict[str, str]:
    """Parse CONTEXT.md into {section_name: content} dict."""
    if not path.exists():
        return {}

    text = path.read_text()
    sections = {}

    for name, (start, end) in SECTION_MARKERS.items():
        s = text.find(start)
        e = text.find(end)
        if s != -1 and e != -1:
            sections[name] = text[s + len(start):e].strip()

    return sections


def _write_context(path: Path, sections: dict[str, str], repo_name: str):
    """Write all sections back to CONTEXT.md."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {repo_name} — context map",
        f"*Generated by contextmap. Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}.*",
        "*Read this file at session start. Do not edit managed sections — edit `## notes` only.*",
        "",
    ]

    for name in SECTION_ORDER:
        start, end = SECTION_MARKERS[name]
        content = sections.get(name, "")
        heading = name.replace("_", " ").title()
        lines += [
            f"## {heading}",
            "",
            start,
            content,
            end,
            "",
        ]

    path.write_text("\n".join(lines))


# ─── Section generators ──────────────────────────────────────────────────────

def _build_project_section(store: GraphStore, root: Path) -> str:
    """Static description: what this project is."""
    s = store.stats()
    name = root.resolve().name

    # Detect language breakdown
    with store._conn() as conn:
        exts = conn.execute("""
            SELECT REPLACE(source_file, RTRIM(source_file, REPLACE(source_file, '.', '')), '') as ext,
                   COUNT(*) as cnt
            FROM nodes WHERE kind='file' AND source_file != ''
            GROUP BY ext ORDER BY cnt DESC LIMIT 5
        """).fetchall()

    lang_hints = []
    ext_map = {
        ".py": "Python", ".js": "JavaScript", ".ts": "TypeScript",
        ".tsx": "TypeScript/React", ".jsx": "JavaScript/React",
        ".go": "Go", ".rs": "Rust", ".java": "Java",
        ".rb": "Ruby", ".cs": "C#",
    }
    seen: set = set()
    for row in exts:
        ext = row["ext"] if row["ext"] else ""
        lang = ext_map.get(ext)
        if lang and lang not in seen:
            lang_hints.append(lang)
            seen.add(lang)

    langs = ", ".join(lang_hints) if lang_hints else "multiple languages"

    lines = [
        f"**Repo:** `{name}`",
        f"**Language:** {langs}",
        f"**Scale:** {s.files} files · {s.nodes} symbols · {s.edges} relationships",
        "",
        "<!-- Add a one-line description here if ctxmap didn't detect one -->",
    ]

    # Try to pull description from README
    for readme in [root / "README.md", root / "readme.md"]:
        if readme.exists():
            text = readme.read_text()[:2000]
            # First non-heading paragraph
            for line in text.splitlines():
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith("!") and len(line) > 30:
                    lines[4] = f"**About:** {line[:200]}"
                    break
            break

    return "\n".join(lines)


def _build_architecture_section(store: GraphStore, root: Path) -> str:
    """Module map: what each file does, internal dependencies."""
    with store._conn() as conn:
        # Files with function counts, excluding tests
        files = conn.execute("""
            SELECT source_file, COUNT(*) as fn_count
            FROM nodes WHERE kind='function' AND source_file != ''
            AND source_file NOT LIKE '%test%' AND source_file NOT LIKE '%spec%'
            GROUP BY source_file ORDER BY fn_count DESC LIMIT 20
        """).fetchall()

        # Internal imports only (relative = same package)
        internal_imports = conn.execute("""
            SELECT source, target FROM edges
            WHERE relation='imports' AND target LIKE '.%'
            AND source NOT LIKE '%test%'
        """).fetchall()

        # Classes
        classes = conn.execute("""
            SELECT label, source_file, source_location FROM nodes
            WHERE kind='class' AND source_file != ''
            AND source_file NOT LIKE '%test%'
            GROUP BY label, source_file
        """).fetchall()

    # Build module dep map (deduplicated)
    deps: dict[str, set[str]] = {}
    for row in internal_imports:
        src = Path(row["source"]).name
        tgt = row["target"].lstrip(".")
        if tgt:
            deps.setdefault(src, set()).add(tgt)

    # Filter to repo files only (deduplicated)
    seen_files: dict[str, int] = {}
    for r in files:
        name = Path(r["source_file"]).name
        if name not in seen_files:
            seen_files[name] = r["fn_count"]

    lines = ["**Module map:**", ""]
    for fname, fn_count in sorted(seen_files.items(), key=lambda x: -x[1]):
        dep_list = sorted(deps.get(fname, set()))
        dep_str = f" → {', '.join(dep_list)}" if dep_list else ""
        lines.append(f"- `{fname}` ({fn_count} fns){dep_str}")

    if classes:
        lines += ["", "**Key classes:**", ""]
        seen_classes = set()
        for c in classes:
            label = c["label"]
            if label in seen_classes or label in ("Handler",):
                continue
            seen_classes.add(label)
            fname = Path(c["source_file"]).name
            loc = c["source_location"] or ""
            lines.append(f"- `{label}` in `{fname}` {loc}")

    return "\n".join(lines)


def _build_conventions_section(store: GraphStore, root: Path) -> str:
    """Detect coding patterns and conventions from the codebase."""
    lines = ["**Detected patterns:**", ""]

    with store._conn() as conn:
        # Naming patterns from function names
        fns = conn.execute("""
            SELECT label FROM nodes WHERE kind='function'
            AND source_file NOT LIKE '%test%'
            AND label NOT LIKE '__%__'
            LIMIT 200
        """).fetchall()

        # Rationale comments
        rationale = conn.execute("""
            SELECT label FROM nodes WHERE kind='rationale' LIMIT 10
        """).fetchall()

        # Test files
        test_files = conn.execute("""
            SELECT DISTINCT source_file FROM nodes
            WHERE source_file LIKE '%test%' OR source_file LIKE '%spec%'
            LIMIT 5
        """).fetchall()

    fn_names = [r["label"] for r in fns]

    # Detect async pattern
    async_count = sum(1 for n in fn_names if n.startswith("async_") or "_async" in n)
    if async_count > 2:
        lines.append("- Async functions present (`async_*` pattern)")

    # Detect private convention
    private_count = sum(1 for n in fn_names if n.startswith("_") and not n.startswith("__"))
    if private_count > 3:
        lines.append("- Private functions use `_prefix` convention")

    # Detect test convention
    test_fn_count = sum(1 for n in fn_names if n.startswith("test_"))
    if test_fn_count > 0:
        lines.append(f"- Tests use `test_*` naming ({test_fn_count} test functions detected)")

    if test_files:
        test_paths = [Path(r["source_file"]).name for r in test_files]
        lines.append(f"- Test files: {', '.join(f'`{p}`' for p in test_paths[:3])}")

    # Detect getter/setter pattern
    getter_count = sum(1 for n in fn_names if n.startswith("get_"))
    sum(1 for n in fn_names if n.startswith("set_"))
    if getter_count > 3:
        lines.append("- Uses `get_*` / `set_*` accessor pattern")

    # Rationale comments
    if rationale:
        lines += ["", "**Design notes from code comments:**", ""]
        for r in rationale[:5]:
            lines.append(f"- {r['label']}")

    if len(lines) <= 2:
        lines.append("- No strong conventions detected yet — add more code for better detection")

    return "\n".join(lines)


def _build_hot_files_section(store: GraphStore, root: Path) -> str:
    """Most-connected repo files — what matters most to understand."""
    G = store.nx_graph()

    # Degree of file nodes only, filtered to actual repo files
    file_degrees = []
    for node_id, data in G.nodes(data=True):
        if (data.get("kind") == "file"
                and data.get("source_file")
                and "test" not in node_id.lower()
                and "spec" not in node_id.lower()):
            # Deduplicate by label
            file_degrees.append((
                Path(data["source_file"]).name,
                data["source_file"],
                G.degree(node_id),
            ))

    # Deduplicate
    seen = {}
    for name, path, deg in file_degrees:
        if name not in seen or deg > seen[name][1]:
            seen[name] = (path, deg)

    top = sorted(seen.items(), key=lambda x: -x[1][1])[:8]

    if not top:
        return "No hot files detected yet — run `contextmap build` first."

    lines = ["**Most connected files (understand these first):**", ""]
    for name, (fpath, degree) in top:
        rel = Path(fpath)
        try:
            rel = Path(fpath).relative_to(root)
        except ValueError:
            rel = Path(name)
        lines.append(f"- `{rel}` — {degree} connections")

    return "\n".join(lines)


def _build_recent_section(store: GraphStore, root: Path) -> str:
    """Files changed in last 7 days via git log."""
    try:
        import subprocess
        result = subprocess.run(
            ["git", "log", "--since=7 days ago", "--name-only",
             "--pretty=format:%ad|%s", "--date=short"],
            capture_output=True, text=True, cwd=root, timeout=5
        )
        if result.returncode != 0 or not result.stdout.strip():
            return _recent_from_hashes(store, root)

        lines = ["**Changed in the last 7 days:**", ""]
        commits: list[tuple[str, str, list[str]]] = []
        current_meta = None
        current_files: list[str] = []

        for line in result.stdout.splitlines():
            line = line.strip()
            if not line:
                if current_meta and current_files:
                    commits.append((*current_meta, current_files))
                    current_files = []
                    current_meta = None
            elif "|" in line and not line.startswith(" "):
                parts = line.split("|", 1)
                if len(parts) == 2:
                    current_meta = (parts[0].strip(), parts[1].strip()[:60])
            elif current_meta:
                if line.endswith((".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".java")):
                    current_files.append(line)

        if current_meta and current_files:
            commits.append((*current_meta, current_files))

        if not commits:
            return _recent_from_hashes(store, root)

        for date, msg, files in commits[:5]:
            lines.append(f"**{date}** — {msg}")
            for f in files[:4]:
                lines.append(f"  - `{Path(f).name}`")
            lines.append("")

        return "\n".join(lines).strip()

    except Exception:
        return _recent_from_hashes(store, root)


def _recent_from_hashes(store: GraphStore, root: Path) -> str:
    """Fallback: show recently updated files from hash store."""
    with store._conn() as conn:
        rows = conn.execute("""
            SELECT path, updated_at FROM file_hashes
            ORDER BY updated_at DESC LIMIT 8
        """).fetchall()

    if not rows:
        return "No recent changes tracked yet."

    lines = ["**Recently indexed files:**", ""]
    for row in rows:
        name = Path(row["path"]).name
        updated = row["updated_at"][:10] if row["updated_at"] else ""
        lines.append(f"- `{name}` {updated}")

    return "\n".join(lines)


# ─── Section hash tracking ────────────────────────────────────────────────────

def _load_section_hashes(root: Path) -> dict[str, str]:
    meta = root / META_FILE
    if meta.exists():
        try:
            return json.loads(meta.read_text())
        except Exception:
            pass
    return {}


def _save_section_hashes(root: Path, hashes: dict[str, str]):
    meta = root / META_FILE
    meta.parent.mkdir(parents=True, exist_ok=True)
    meta.write_text(json.dumps(hashes, indent=2))


def _section_input_hash(store: GraphStore, section: str, root: Path) -> str:
    """Compute a hash of the inputs for a given section."""
    s = store.stats()

    if section == "project":
        readme = (root / "README.md")
        readme_hash = hashlib.sha256(readme.read_bytes()).hexdigest()[:8] if readme.exists() else ""
        return _hash_inputs(s.files, readme_hash)

    elif section == "architecture":
        with store._conn() as conn:
            files = conn.execute("SELECT source_file, COUNT(*) FROM nodes WHERE kind='function' GROUP BY source_file").fetchall()
            imports = conn.execute("SELECT source, target FROM edges WHERE relation='imports' AND target LIKE '.%'").fetchall()
        return _hash_inputs(sorted(f["source_file"] for f in files), sorted(f"{r['source']}->{r['target']}" for r in imports))

    elif section == "conventions":
        with store._conn() as conn:
            fns = conn.execute("SELECT label FROM nodes WHERE kind='function' LIMIT 200").fetchall()
        return _hash_inputs(sorted(r["label"] for r in fns))

    elif section == "hot_files":
        return _hash_inputs(s.nodes, s.edges)

    elif section == "recent":
        with store._conn() as conn:
            hashes = conn.execute("SELECT path, hash FROM file_hashes ORDER BY updated_at DESC LIMIT 10").fetchall()
        return _hash_inputs([(r["path"], r["hash"]) for r in hashes])

    return _hash_inputs(s.nodes, s.edges)


# ─── Public API ──────────────────────────────────────────────────────────────

SECTION_BUILDERS = {
    "project": _build_project_section,
    "architecture": _build_architecture_section,
    "conventions": _build_conventions_section,
    "hot_files": _build_hot_files_section,
    "recent": _build_recent_section,
}


def build_context(store: GraphStore, root: Path, force: bool = False) -> dict:
    """
    Build or update CONTEXT.md.
    Only rewrites sections whose source inputs changed.
    Returns stats: {section: 'updated'|'cached'|'kept'}.
    """
    context_path = root / CONTEXT_FILE
    existing = _read_sections(context_path)
    stored_hashes = _load_section_hashes(root)
    new_hashes = dict(stored_hashes)
    repo_name = root.name

    stats = {}
    updated_sections = dict(existing)

    for section in SECTION_ORDER:
        # Notes section: NEVER touched
        if section == "notes":
            if "notes" not in existing:
                updated_sections["notes"] = (
                    "<!-- Add your own notes here. This section is never overwritten by contextmap. -->\n\n"
                    "- "
                )
                stats["notes"] = "created"
            else:
                stats["notes"] = "kept"
            continue

        # Check if inputs changed
        input_hash = _section_input_hash(store, section, root)
        if not force and stored_hashes.get(section) == input_hash and section in existing:
            stats[section] = "cached"
            continue

        # Build the section
        builder = SECTION_BUILDERS.get(section)
        if builder:
            try:
                content = builder(store, root)
                updated_sections[section] = content
                new_hashes[section] = input_hash
                stats[section] = "updated"
                logger.info(f"Section '{section}' updated")
            except Exception as e:
                logger.warning(f"Section '{section}' failed: {e}")
                stats[section] = "error"

    _write_context(context_path, updated_sections, repo_name)
    _save_section_hashes(root, new_hashes)
    return stats


def token_estimate(root: Path) -> int:
    """Rough token count of current CONTEXT.md."""
    path = root / CONTEXT_FILE
    if not path.exists():
        return 0
    return len(path.read_text()) // 4
